//
// Created by kevin on 10.02.2022.
//

#ifndef COMPUTERGRAFIK_PRAKTIKUM_TERRAINCHUNK_H
#define COMPUTERGRAFIK_PRAKTIKUM_TERRAINCHUNK_H


class TerrainChunk {

};


#endif //COMPUTERGRAFIK_PRAKTIKUM_TERRAINCHUNK_H
